<?php

namespace DuckTVBundle\Repository;

/**
 * DiffusionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiffusionRepository extends \Doctrine\ORM\EntityRepository
{
}
